// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaVehicleInfo.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "CarlaVehicleInfo.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace carla_msgs {

namespace msg {



CarlaVehicleInfo::CarlaVehicleInfo()
{
}

CarlaVehicleInfo::~CarlaVehicleInfo()
{
}

CarlaVehicleInfo::CarlaVehicleInfo(
        const CarlaVehicleInfo& x)
{
    m_id = x.m_id;
    m_type = x.m_type;
    m_rolename = x.m_rolename;
    m_wheels = x.m_wheels;
    m_max_rpm = x.m_max_rpm;
    m_moi = x.m_moi;
    m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;
    m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;
    m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;
    m_use_gear_autobox = x.m_use_gear_autobox;
    m_gear_switch_time = x.m_gear_switch_time;
    m_clutch_strength = x.m_clutch_strength;
    m_mass = x.m_mass;
    m_drag_coefficient = x.m_drag_coefficient;
    m_center_of_mass = x.m_center_of_mass;
    m_shape = x.m_shape;
}

CarlaVehicleInfo::CarlaVehicleInfo(
        CarlaVehicleInfo&& x) noexcept
{
    m_id = x.m_id;
    m_type = std::move(x.m_type);
    m_rolename = std::move(x.m_rolename);
    m_wheels = std::move(x.m_wheels);
    m_max_rpm = x.m_max_rpm;
    m_moi = x.m_moi;
    m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;
    m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;
    m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;
    m_use_gear_autobox = x.m_use_gear_autobox;
    m_gear_switch_time = x.m_gear_switch_time;
    m_clutch_strength = x.m_clutch_strength;
    m_mass = x.m_mass;
    m_drag_coefficient = x.m_drag_coefficient;
    m_center_of_mass = std::move(x.m_center_of_mass);
    m_shape = std::move(x.m_shape);
}

CarlaVehicleInfo& CarlaVehicleInfo::operator =(
        const CarlaVehicleInfo& x)
{

    m_id = x.m_id;
    m_type = x.m_type;
    m_rolename = x.m_rolename;
    m_wheels = x.m_wheels;
    m_max_rpm = x.m_max_rpm;
    m_moi = x.m_moi;
    m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;
    m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;
    m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;
    m_use_gear_autobox = x.m_use_gear_autobox;
    m_gear_switch_time = x.m_gear_switch_time;
    m_clutch_strength = x.m_clutch_strength;
    m_mass = x.m_mass;
    m_drag_coefficient = x.m_drag_coefficient;
    m_center_of_mass = x.m_center_of_mass;
    m_shape = x.m_shape;
    return *this;
}

CarlaVehicleInfo& CarlaVehicleInfo::operator =(
        CarlaVehicleInfo&& x) noexcept
{

    m_id = x.m_id;
    m_type = std::move(x.m_type);
    m_rolename = std::move(x.m_rolename);
    m_wheels = std::move(x.m_wheels);
    m_max_rpm = x.m_max_rpm;
    m_moi = x.m_moi;
    m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;
    m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;
    m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;
    m_use_gear_autobox = x.m_use_gear_autobox;
    m_gear_switch_time = x.m_gear_switch_time;
    m_clutch_strength = x.m_clutch_strength;
    m_mass = x.m_mass;
    m_drag_coefficient = x.m_drag_coefficient;
    m_center_of_mass = std::move(x.m_center_of_mass);
    m_shape = std::move(x.m_shape);
    return *this;
}

bool CarlaVehicleInfo::operator ==(
        const CarlaVehicleInfo& x) const
{
    return (m_id == x.m_id &&
           m_type == x.m_type &&
           m_rolename == x.m_rolename &&
           m_wheels == x.m_wheels &&
           m_max_rpm == x.m_max_rpm &&
           m_moi == x.m_moi &&
           m_damping_rate_full_throttle == x.m_damping_rate_full_throttle &&
           m_damping_rate_zero_throttle_clutch_engaged == x.m_damping_rate_zero_throttle_clutch_engaged &&
           m_damping_rate_zero_throttle_clutch_disengaged == x.m_damping_rate_zero_throttle_clutch_disengaged &&
           m_use_gear_autobox == x.m_use_gear_autobox &&
           m_gear_switch_time == x.m_gear_switch_time &&
           m_clutch_strength == x.m_clutch_strength &&
           m_mass == x.m_mass &&
           m_drag_coefficient == x.m_drag_coefficient &&
           m_center_of_mass == x.m_center_of_mass &&
           m_shape == x.m_shape);
}

bool CarlaVehicleInfo::operator !=(
        const CarlaVehicleInfo& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member id
 * @param _id New value for member id
 */
void CarlaVehicleInfo::id(
        uint32_t _id)
{
    m_id = _id;
}

/*!
 * @brief This function returns the value of member id
 * @return Value of member id
 */
uint32_t CarlaVehicleInfo::id() const
{
    return m_id;
}

/*!
 * @brief This function returns a reference to member id
 * @return Reference to member id
 */
uint32_t& CarlaVehicleInfo::id()
{
    return m_id;
}


/*!
 * @brief This function copies the value in member type
 * @param _type New value to be copied in member type
 */
void CarlaVehicleInfo::type(
        const std::string& _type)
{
    m_type = _type;
}

/*!
 * @brief This function moves the value in member type
 * @param _type New value to be moved in member type
 */
void CarlaVehicleInfo::type(
        std::string&& _type)
{
    m_type = std::move(_type);
}

/*!
 * @brief This function returns a constant reference to member type
 * @return Constant reference to member type
 */
const std::string& CarlaVehicleInfo::type() const
{
    return m_type;
}

/*!
 * @brief This function returns a reference to member type
 * @return Reference to member type
 */
std::string& CarlaVehicleInfo::type()
{
    return m_type;
}


/*!
 * @brief This function copies the value in member rolename
 * @param _rolename New value to be copied in member rolename
 */
void CarlaVehicleInfo::rolename(
        const std::string& _rolename)
{
    m_rolename = _rolename;
}

/*!
 * @brief This function moves the value in member rolename
 * @param _rolename New value to be moved in member rolename
 */
void CarlaVehicleInfo::rolename(
        std::string&& _rolename)
{
    m_rolename = std::move(_rolename);
}

/*!
 * @brief This function returns a constant reference to member rolename
 * @return Constant reference to member rolename
 */
const std::string& CarlaVehicleInfo::rolename() const
{
    return m_rolename;
}

/*!
 * @brief This function returns a reference to member rolename
 * @return Reference to member rolename
 */
std::string& CarlaVehicleInfo::rolename()
{
    return m_rolename;
}


/*!
 * @brief This function copies the value in member wheels
 * @param _wheels New value to be copied in member wheels
 */
void CarlaVehicleInfo::wheels(
        const std::vector<carla_msgs::msg::CarlaVehicleInfoWheel>& _wheels)
{
    m_wheels = _wheels;
}

/*!
 * @brief This function moves the value in member wheels
 * @param _wheels New value to be moved in member wheels
 */
void CarlaVehicleInfo::wheels(
        std::vector<carla_msgs::msg::CarlaVehicleInfoWheel>&& _wheels)
{
    m_wheels = std::move(_wheels);
}

/*!
 * @brief This function returns a constant reference to member wheels
 * @return Constant reference to member wheels
 */
const std::vector<carla_msgs::msg::CarlaVehicleInfoWheel>& CarlaVehicleInfo::wheels() const
{
    return m_wheels;
}

/*!
 * @brief This function returns a reference to member wheels
 * @return Reference to member wheels
 */
std::vector<carla_msgs::msg::CarlaVehicleInfoWheel>& CarlaVehicleInfo::wheels()
{
    return m_wheels;
}


/*!
 * @brief This function sets a value in member max_rpm
 * @param _max_rpm New value for member max_rpm
 */
void CarlaVehicleInfo::max_rpm(
        float _max_rpm)
{
    m_max_rpm = _max_rpm;
}

/*!
 * @brief This function returns the value of member max_rpm
 * @return Value of member max_rpm
 */
float CarlaVehicleInfo::max_rpm() const
{
    return m_max_rpm;
}

/*!
 * @brief This function returns a reference to member max_rpm
 * @return Reference to member max_rpm
 */
float& CarlaVehicleInfo::max_rpm()
{
    return m_max_rpm;
}


/*!
 * @brief This function sets a value in member moi
 * @param _moi New value for member moi
 */
void CarlaVehicleInfo::moi(
        float _moi)
{
    m_moi = _moi;
}

/*!
 * @brief This function returns the value of member moi
 * @return Value of member moi
 */
float CarlaVehicleInfo::moi() const
{
    return m_moi;
}

/*!
 * @brief This function returns a reference to member moi
 * @return Reference to member moi
 */
float& CarlaVehicleInfo::moi()
{
    return m_moi;
}


/*!
 * @brief This function sets a value in member damping_rate_full_throttle
 * @param _damping_rate_full_throttle New value for member damping_rate_full_throttle
 */
void CarlaVehicleInfo::damping_rate_full_throttle(
        float _damping_rate_full_throttle)
{
    m_damping_rate_full_throttle = _damping_rate_full_throttle;
}

/*!
 * @brief This function returns the value of member damping_rate_full_throttle
 * @return Value of member damping_rate_full_throttle
 */
float CarlaVehicleInfo::damping_rate_full_throttle() const
{
    return m_damping_rate_full_throttle;
}

/*!
 * @brief This function returns a reference to member damping_rate_full_throttle
 * @return Reference to member damping_rate_full_throttle
 */
float& CarlaVehicleInfo::damping_rate_full_throttle()
{
    return m_damping_rate_full_throttle;
}


/*!
 * @brief This function sets a value in member damping_rate_zero_throttle_clutch_engaged
 * @param _damping_rate_zero_throttle_clutch_engaged New value for member damping_rate_zero_throttle_clutch_engaged
 */
void CarlaVehicleInfo::damping_rate_zero_throttle_clutch_engaged(
        float _damping_rate_zero_throttle_clutch_engaged)
{
    m_damping_rate_zero_throttle_clutch_engaged = _damping_rate_zero_throttle_clutch_engaged;
}

/*!
 * @brief This function returns the value of member damping_rate_zero_throttle_clutch_engaged
 * @return Value of member damping_rate_zero_throttle_clutch_engaged
 */
float CarlaVehicleInfo::damping_rate_zero_throttle_clutch_engaged() const
{
    return m_damping_rate_zero_throttle_clutch_engaged;
}

/*!
 * @brief This function returns a reference to member damping_rate_zero_throttle_clutch_engaged
 * @return Reference to member damping_rate_zero_throttle_clutch_engaged
 */
float& CarlaVehicleInfo::damping_rate_zero_throttle_clutch_engaged()
{
    return m_damping_rate_zero_throttle_clutch_engaged;
}


/*!
 * @brief This function sets a value in member damping_rate_zero_throttle_clutch_disengaged
 * @param _damping_rate_zero_throttle_clutch_disengaged New value for member damping_rate_zero_throttle_clutch_disengaged
 */
void CarlaVehicleInfo::damping_rate_zero_throttle_clutch_disengaged(
        float _damping_rate_zero_throttle_clutch_disengaged)
{
    m_damping_rate_zero_throttle_clutch_disengaged = _damping_rate_zero_throttle_clutch_disengaged;
}

/*!
 * @brief This function returns the value of member damping_rate_zero_throttle_clutch_disengaged
 * @return Value of member damping_rate_zero_throttle_clutch_disengaged
 */
float CarlaVehicleInfo::damping_rate_zero_throttle_clutch_disengaged() const
{
    return m_damping_rate_zero_throttle_clutch_disengaged;
}

/*!
 * @brief This function returns a reference to member damping_rate_zero_throttle_clutch_disengaged
 * @return Reference to member damping_rate_zero_throttle_clutch_disengaged
 */
float& CarlaVehicleInfo::damping_rate_zero_throttle_clutch_disengaged()
{
    return m_damping_rate_zero_throttle_clutch_disengaged;
}


/*!
 * @brief This function sets a value in member use_gear_autobox
 * @param _use_gear_autobox New value for member use_gear_autobox
 */
void CarlaVehicleInfo::use_gear_autobox(
        bool _use_gear_autobox)
{
    m_use_gear_autobox = _use_gear_autobox;
}

/*!
 * @brief This function returns the value of member use_gear_autobox
 * @return Value of member use_gear_autobox
 */
bool CarlaVehicleInfo::use_gear_autobox() const
{
    return m_use_gear_autobox;
}

/*!
 * @brief This function returns a reference to member use_gear_autobox
 * @return Reference to member use_gear_autobox
 */
bool& CarlaVehicleInfo::use_gear_autobox()
{
    return m_use_gear_autobox;
}


/*!
 * @brief This function sets a value in member gear_switch_time
 * @param _gear_switch_time New value for member gear_switch_time
 */
void CarlaVehicleInfo::gear_switch_time(
        float _gear_switch_time)
{
    m_gear_switch_time = _gear_switch_time;
}

/*!
 * @brief This function returns the value of member gear_switch_time
 * @return Value of member gear_switch_time
 */
float CarlaVehicleInfo::gear_switch_time() const
{
    return m_gear_switch_time;
}

/*!
 * @brief This function returns a reference to member gear_switch_time
 * @return Reference to member gear_switch_time
 */
float& CarlaVehicleInfo::gear_switch_time()
{
    return m_gear_switch_time;
}


/*!
 * @brief This function sets a value in member clutch_strength
 * @param _clutch_strength New value for member clutch_strength
 */
void CarlaVehicleInfo::clutch_strength(
        float _clutch_strength)
{
    m_clutch_strength = _clutch_strength;
}

/*!
 * @brief This function returns the value of member clutch_strength
 * @return Value of member clutch_strength
 */
float CarlaVehicleInfo::clutch_strength() const
{
    return m_clutch_strength;
}

/*!
 * @brief This function returns a reference to member clutch_strength
 * @return Reference to member clutch_strength
 */
float& CarlaVehicleInfo::clutch_strength()
{
    return m_clutch_strength;
}


/*!
 * @brief This function sets a value in member mass
 * @param _mass New value for member mass
 */
void CarlaVehicleInfo::mass(
        float _mass)
{
    m_mass = _mass;
}

/*!
 * @brief This function returns the value of member mass
 * @return Value of member mass
 */
float CarlaVehicleInfo::mass() const
{
    return m_mass;
}

/*!
 * @brief This function returns a reference to member mass
 * @return Reference to member mass
 */
float& CarlaVehicleInfo::mass()
{
    return m_mass;
}


/*!
 * @brief This function sets a value in member drag_coefficient
 * @param _drag_coefficient New value for member drag_coefficient
 */
void CarlaVehicleInfo::drag_coefficient(
        float _drag_coefficient)
{
    m_drag_coefficient = _drag_coefficient;
}

/*!
 * @brief This function returns the value of member drag_coefficient
 * @return Value of member drag_coefficient
 */
float CarlaVehicleInfo::drag_coefficient() const
{
    return m_drag_coefficient;
}

/*!
 * @brief This function returns a reference to member drag_coefficient
 * @return Reference to member drag_coefficient
 */
float& CarlaVehicleInfo::drag_coefficient()
{
    return m_drag_coefficient;
}


/*!
 * @brief This function copies the value in member center_of_mass
 * @param _center_of_mass New value to be copied in member center_of_mass
 */
void CarlaVehicleInfo::center_of_mass(
        const geometry_msgs::msg::Vector3& _center_of_mass)
{
    m_center_of_mass = _center_of_mass;
}

/*!
 * @brief This function moves the value in member center_of_mass
 * @param _center_of_mass New value to be moved in member center_of_mass
 */
void CarlaVehicleInfo::center_of_mass(
        geometry_msgs::msg::Vector3&& _center_of_mass)
{
    m_center_of_mass = std::move(_center_of_mass);
}

/*!
 * @brief This function returns a constant reference to member center_of_mass
 * @return Constant reference to member center_of_mass
 */
const geometry_msgs::msg::Vector3& CarlaVehicleInfo::center_of_mass() const
{
    return m_center_of_mass;
}

/*!
 * @brief This function returns a reference to member center_of_mass
 * @return Reference to member center_of_mass
 */
geometry_msgs::msg::Vector3& CarlaVehicleInfo::center_of_mass()
{
    return m_center_of_mass;
}


/*!
 * @brief This function copies the value in member shape
 * @param _shape New value to be copied in member shape
 */
void CarlaVehicleInfo::shape(
        const shape_msgs::msg::SolidPrimitive& _shape)
{
    m_shape = _shape;
}

/*!
 * @brief This function moves the value in member shape
 * @param _shape New value to be moved in member shape
 */
void CarlaVehicleInfo::shape(
        shape_msgs::msg::SolidPrimitive&& _shape)
{
    m_shape = std::move(_shape);
}

/*!
 * @brief This function returns a constant reference to member shape
 * @return Constant reference to member shape
 */
const shape_msgs::msg::SolidPrimitive& CarlaVehicleInfo::shape() const
{
    return m_shape;
}

/*!
 * @brief This function returns a reference to member shape
 * @return Reference to member shape
 */
shape_msgs::msg::SolidPrimitive& CarlaVehicleInfo::shape()
{
    return m_shape;
}




} // namespace msg


} // namespace carla_msgs
// Include auxiliary functions like for serializing/deserializing.
#include "CarlaVehicleInfoCdrAux.ipp"

